### PR TITLE
Update code / documentation to work with scotty version >= 0.10.*

### PR DESCRIPTION
**Pull request by cmoresid**

### CODE REVIEW

**Comment by tfausak** [comment]
Thanks for submitting this pull request. The changes look great! I haven't kept up with Scotty, so I don't know how things have changed. Why did you decide to stick with LTS 5.8 instead of 6.9 in 1b0d863e47faa7179a946efbe20334bac230a600?

**Comment by cmoresid** [comment]
No problem! Thanks for creating this example in the first place. It was incredibly helpful in trying to learn Scotty!

I changed it from 6.9 back to 5.8 because I wasn't quite sure if updating to 6.9 would break the CI build. I'm still new to Haskell and Travis CI :) LTS 6.9 along with scotty 0.11.* worked fine on my machine though.  I can change back to what I had originally if you'd like.

**Comment by cmoresid** [comment]
Ok sounds good! I changed it back to what I originally had and Travis didn't seem to have a problem with it.

**Comment by tfausak** [comment]
Thanks again! This is great!

**Pull request merged**
